---
# refresh website from git to webservers
- name: Update website
  hosts: rhel
  become: yes

  vars:
    git_base: 

  tasks:
  - name: Copy the code from repository
    git:
      repo: "{{ git_base }}/website_demo.git"
      dest: /var/www/html/
