---
- name: Listen for events on a webhook from Terraform Actions
  hosts: all
  execution_strategy: parallel
  sources:
    - name: Listen for alerts from Terraform
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5015

  rules:
    - name: Terraform Post Create Action

